let citations = [
  ["La vie est un mystère qu'il faut vivre, et non un problème à résoudre.", "Gandhi"],
  ["Le plus grand risque est de ne prendre aucun risque.", "Mark Zuckerberg"],
  ["Méritez votre statut de leader chaque jour.", "Mickael Jordan"],
  ["Soyez le changement que vous voulez voir dans le monde.", "Gandhi"],
  ["A chaque fois que vous vous retrouvez du même côté que la majorité, il est temps de prendre du recul, et de réfléchir.", "Mark Twain"],
  ["Seulement ceux qui prendront le risque d’aller trop loin découvriront jusqu’où on peut aller.", "T.S Elliot"],
  ["Le succès c’est tomber sept fois, se relever huit.", "Proverbe japonais"],
  ["Dans vingt ans vous serez plus déçus par les choses que vous n’avez pas faites que par celles que vous avez faites. Alors sortez des sentiers battus. Mettez les voiles. Explorez. Rêvez. Découvrez.", "Mark Twain"],
  ["Si vous attendez pour agir, tout ce que vous gagnerez, avec le temps, c’est de l’âge.", "Brian Tracy"],
  ["Quand on concentre son attention sur un seul projet, l’esprit suggère constamment des idées et des améliorations qui lui échapperaient s’il était occupé avec plusieurs projets en même temps.", "P.T. Barnum"],
  ["Se dédier à faire tout ce que l’on peut pour aider les autres à obtenir ce qu’ils veulent, c’est la clé du succès.", "Brian Sher"],
  ["Si vous pensez que vous êtes trop petit pour avoir de l’impact, essayez d’aller au lit avec un moustique.", "Anita Roddick"],
  ["Ne jugez pas chaque jour sur ce que vous récoltez, mais sur les graines que vous semez.", "Robert Louis Stevenson"],
  ["L’action est la clé fondamentale de tout succès.", "Pablo Picasso"],
  ["Le succès, c’est se promener d’échecs en échecs tout en restant motivé.", "Winston Churchill"],
  ["Votre avenir est créé par ce que vous faîtes aujourd’hui, pas demain.", "Robert T. Kiyosaki"],
  ["Ne vous découragez pas, c’est souvent la dernière clef du trousseau qui ouvre la porte.", "Zig Ziglar"],
  ["Pour gagner votre vie, apprenez à l’école. Pour gagner une fortune, apprenez par vous-même.", "Brian Tracy"],
  ["Les gagnants trouvent des moyens, les perdants des excuses…", "F. D. Roosevelt"],
  ["Vous n’êtes jamais trop vieux pour vous fixer de nouveaux buts, ou rendre vos rêves réalité.", "C.S. Lewis"],
  ["Un pessimiste voit la difficulté dans chaque opportunité. Un optimiste voit une opportunité dans chaque difficulté.", "Winston Churchill"],
  ['Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. Si vous aimez ce que vous faites, vous réussirez.', 'Albert Schweitzer'],
  ['La seule façon de faire du bon travail est d’aimer ce que vous faites.', 'Steve Jobs'],
  ['L’action est la clé fondamentale de tout succès.', 'Pablo Picasso'],
  ['Le meilleur moment pour planter un arbre était il y a 20 ans. Le deuxième meilleur moment est maintenant.', 'Proverbe Chinois'],
  ['Commencez par faire le nécessaire, puis faites ce qu’il est possible de faire, et tout à coup, vous faites l’impossible.', 'Saint François d\'Assise'],
  ['Croyez en vous-même. Vous êtes plus courageux que vous ne le pensez, plus talentueux que vous ne le savez, et capable de plus que vous ne l\'imaginez.', 'Roy T. Bennett'],
  ['N’ayez pas peur de l’échec. Ayez peur de ne pas essayer.', 'Michael Jordan'], 
  ['La vie, c’est 10% ce qui vous arrive et 90% comment vous y réagissez.', 'Charles R. Swindoll'], 
  ['Ils ne savaient pas que c’était impossible, alors ils l’ont fait.', 'Mark Twain'], 
  ['Peu importe la lenteur avec laquelle vous avancez, tant que vous ne vous arrêtez pas.', 'Confucius'],
  ['Ce n’est pas la force, mais la persévérance qui fait les grandes œuvres.', 'Samuel Johnson'], 
  ['Notre plus grande gloire n’est pas de ne jamais tomber, mais de nous relever à chaque fois que nous tombons.', 'Confucius'],
  ['Le courage n\'est pas l\'absence de peur, mais la capacité de la vaincre.', 'Nelson Mandela'], 
  ['Le chemin vers le succès et le chemin vers l\'échec sont presque exactement les mêmes.', 'Colin R. Davis'], 
  ['Transformez vos blessures en sagesse.', 'Oprah Winfrey'],
  ['Il est toujours trop tôt pour abandonner.', 'Norman Vincent Peale'], 
  ['La motivation vous fait démarrer, l\'habitude vous fait continuer.', 'Jim Ryun'],
  ['Le succès, c\'est d\'aller d\'échec en échec sans perdre son enthousiasme.', 'Winston Churchill'],
  ['Un voyage de mille lieues commence toujours par un premier pas.', 'Lao Tseu'], 
  ['La différence entre le possible et l\'impossible réside dans la détermination d\'un homme.', 'Tommy Lasorda']
  ['Faites de chaque jour votre chef-d’œuvre.', 'John Wooden'],
  ['L\'esprit est tout. Ce que vous pensez, vous le devenez.', 'Bouddha'], 
  ['Quand on ne peut revenir en arrière, on ne doit se préoccuper que de la meilleure façon d’aller de l’avant.', 'Paulo Coelho'], 
  ['Si vous attendez le moment parfait, vous attendrez toute votre vie.', 'Auteur Inconnu'], 
  ['Le but n’est pas d’éviter l’échec, mais de s’en servir comme d’un tremplin.', 'Auteur Inconnu'],
  ['La seule limite à notre épanouissement de demain est nos doutes d’aujourd’hui.', 'Franklin D. Roosevelt'],
  ['Il n’y a qu’une seule façon d’éviter la critique : ne rien faire, ne rien dire et n’être rien.', 'Aristote'],
  ['Ne vous inquiétez pas de l’échec, inquiétez-vous des chances que vous manquez lorsque vous n’essayez même pas.', 'Jack Canfield'],
  ['Le meilleur moyen de prédire l’avenir est de le créer.', 'Peter Drucker'],
  ['Si vous pouvez le rêver, vous pouvez le faire.', 'Walt Disney'],
  ['La discipline est le pont entre les buts et la réalisation.', 'Jim Rohn'],
  ['Ce que nous sommes est le résultat de ce que nous avons pensé.', 'Bouddha'],
  ['La persévérance est la capacité à transformer l’échec en succès.', 'Inconnu'],
  ['Les grands esprits discutent des idées ; les esprits moyens discutent des événements ; les petits esprits discutent des gens.', 'Eleanor Roosevelt'],
  ['Le succès est la somme de petits efforts, répétés jour après jour.', 'Robert Collier'],
  ['Pour réaliser de grandes choses, nous devons non seulement agir, mais aussi rêver; non seulement planifier, mais aussi croire.', 'Anatole France'],
  ['Ce n’est pas parce que les choses sont difficiles que nous n’osons pas, c’est parce que nous n’osons pas qu’elles sont difficiles.', 'Sénèque'],
  ['L’optimisme est la foi qui mène au succès. Rien ne peut être fait sans espoir et confiance.', 'Helen Keller'],
  ['Je ne perds jamais. Soit je gagne, soit j’apprends.', 'Nelson Mandela'],
  ['Chaque moment est un nouveau départ.', 'Auteur Inconnu']
  ['La seule chose qui se dresse entre vous et votre rêve est la volonté d\'essayer et la conviction qu\'il est réellement possible.', 'Joel Brown'],
  ['Le succès est de trébucher d’échec en échec sans perdre son enthousiasme.', 'Winston Churchill'],
  ['On ne découvre pas de terre nouvelle sans consentir à perdre de vue, d’abord et longtemps, tout rivage.', 'André Gide'], 
  ['La difficulté n’est pas de comprendre les idées nouvelles, mais d’échapper aux idées anciennes.', 'John Maynard Keynes'],
  ['La vie est soit une aventure audacieuse, soit rien du tout.', 'Helen Keller'],
  ['Ce n’est pas tant ce que nous faisons, mais la quantité d’amour que nous mettons dans ce que nous faisons.', 'Mère Teresa'],
  ['Vous ratez 100% des tirs que vous ne prenez pas.', 'Wayne Gretzky'],
  ['Il faut toujours viser la lune, car même en cas d’échec, on atterrit dans les étoiles.', 'Oscar Wilde'],
  ['L\'échec est un succès si l\'on en tire des leçons.', 'Malcolm Forbes'],
  ['Le véritable voyage de découverte ne consiste pas à chercher de nouveaux paysages, mais à avoir de nouveaux yeux.', 'Marcel Proust'],
  ['Ne craignez pas de grandir lentement, craignez seulement de rester immobile.', 'Proverbe Chinois'],
  ['Même le plus long des chemins commence par un pas.', 'Lao Tseu'],
  ['La meilleure vengeance est un succès massif.', 'Frank Sinatra'], 
  ['Notre destin n\'est pas en attente, il est dans l\'action.', 'William Jennings Bryan'],
  ['Le futur appartient à ceux qui croient en la beauté de leurs rêves.', 'Eleanor Roosevelt'],
  ['La douleur d’aujourd’hui est la force de demain.', 'Auteur Inconnu'],
  ['Soyez le changement que vous voulez voir dans le monde.', 'Mahatma Gandhi'],
  ['Quand tout semble aller contre vous, souvenez-vous que l’avion décolle toujours contre le vent, pas avec lui.', 'Henry Ford'],
  ['Il n\'y a pas de raccourci vers un endroit qui vaut la peine d\'aller.', 'Beverly Sills'],
  ['Le succès n’est pas final, l’échec n’est pas fatal : c’est le courage de continuer qui compte.', 'Winston Churchill']
  ['L\'ambition est le chemin vers le succès. La persévérance est le véhicule avec lequel vous y arrivez.', 'Bill Bradley'], 
  ['Plus dure sera la bataille, plus douce sera la victoire.', 'Bob Marley'], 
  ['Le meilleur moyen d\'apprécier votre travail est de vous imaginer sans lui.', 'Oscar Wilde'],
  ['Ce que vous obtenez en atteignant vos objectifs n’est pas aussi important que ce que vous devenez en les atteignant.', 'Zig Ziglar'], 
  ['Le succès est la progression constante vers un objectif digne.', 'Earl Nightingale'],
  ['Les défis sont ce qui rend la vie intéressante et les surmonter est ce qui lui donne un sens.', 'Joshua J. Marine'],
  ['La qualité de votre vie est la qualité de vos communications.', 'Tony Robbins'],
  ['Il y a deux types de personnes qui vous diront que vous ne pouvez pas faire la différence dans ce monde : ceux qui ont peur d\'essayer et ceux qui ont peur que vous réussissiez.', 'Ray Goforth'],
  ['Ne craignez pas de grandir lentement, craignez seulement de rester immobile.', 'Proverbe Chinois'],
  ['Pour gagner, il faut se donner les moyens.', 'Léonard de Vinci'],
  ['Le courage de l’action est le seul rempart à la peur.', 'Aristote'],
  ['Une personne avec une nouvelle idée est un original jusqu’à ce que l’idée réussisse.', 'Mark Twain'],
  ['La plus grande découverte de tous les temps est qu’une personne peut changer son avenir en changeant simplement son attitude.', 'Oprah Winfrey'],
  ['L’avenir appartient à ceux qui croient en la beauté de leurs rêves.', 'Eleanor Roosevelt'],
  ['La seule personne que vous êtes destiné à devenir est la personne que vous décidez d’être.', 'Ralph Waldo Emerson'],
  ['Les petits ruisseaux font les grandes rivières.', 'Proverbe Français'],
  ['Ce n’est pas le vent qui décide de votre destination, c’est l’orientation que vous donnez à votre voile.', 'Jim Rohn'],
  ['La différence entre l’ordinaire et l’extraordinaire, c’est ce petit ‘extra’.', 'Jimmy Johnson'],
  ['Ne limitez pas vos défis, défiez vos limites.', 'Jerry Dunn'],
  ['Ne vous arrêtez pas lorsque vous êtes fatigué. Arrêtez-vous lorsque vous avez terminé.', 'Marilyn Monroe']
  ['La plus grande gloire n’est pas de ne jamais tomber, mais de se relever à chaque chute.', 'Nelson Mandela'],
  ['Changez vos pensées et vous changerez votre monde.', 'Norman Vincent Peale'],
  ['Le succès est de faire ce que vous voulez, quand vous voulez, où vous voulez, avec qui vous voulez, autant de fois que vous voulez.', 'Tony Robbins'],
  ['Si vous voulez construire un navire, ne commencez pas par rassembler du bois, couper des planches et distribuer du travail, mais réveillez au sein des hommes le désir de la mer lointaine et infinie.', 'Antoine de Saint-Exupéry'],
  ['La critique est facile, l’art est difficile.', 'Destouches'],
  ['Le secret du changement est de concentrer toute votre énergie non pas à lutter contre l\'ancien, mais à construire le nouveau.', 'Socrate'],
  ['Seule une vie vécue au service des autres est une vie qui vaut la peine d\'être vécue.', 'Albert Einstein'],
  ['La meilleure façon de commencer est d’arrêter de parler et de commencer à faire.', 'Walt Disney'],
  ['Les grands actes sont composés de petits efforts répétés.', 'Mahatma Gandhi'],
  ['Celui qui déplace la montagne est celui qui commence par enlever les petites pierres.', 'Proverbe Chinois'],
  ['Il n’y a pas de vent favorable pour celui qui ne sait pas où il va.', 'Sénèque'],
  ['Ne craignez pas de l’ombre, elle signifie juste qu’il y a une lumière quelque part à proximité.', 'Ruth Renkel'],
  ['Ne jugez pas chaque jour à la récolte que vous faites, mais aux graines que vous semez.', 'Robert Louis Stevenson'],
  ['Ce n’est pas la vitesse qui compte, mais la direction.', 'Auteur Inconnu'],
  ['La patience est un élément clé du succès.', 'Bill Gates'],
  ['Le meilleur moment pour se reposer est quand vous n’avez pas le temps pour cela.', 'Mark Twain'],
  ['La vie est comme faire du vélo. Pour garder l’équilibre, il faut continuer à avancer.', 'Albert Einstein'],
  ['Toutes nos réalisations, tous nos progrès, ont eu leur point de départ dans une idée.', 'Napoleon Hill'],
  ['La volonté de gagner, le désir de réussir, l’envie d’atteindre votre plein potentiel... ce sont les clés qui déverrouilleront la porte de l’excellence personnelle.', 'Confucius'],
  ['Agissez comme si ce que vous faites faisait la différence. Cela en fait une.', 'William James']
];
let emplacementCitation = document.querySelector('#citation');
let auteur = document.querySelector('#auteur');
let btn = document.querySelector('#nouveau');
let dernier = 0;
let nombreAleatoire;
let nombreElementsCitations = citations.length;

function genererNombreEntier(max) {
  return Math.floor(Math.random() * Math.floor(max));
}


function majContenu () {
  nombreAleatoire = genererNombreEntier(nombreElementsCitations);
  emplacementCitation.textContent = citations[nombreAleatoire][0];
  auteur.textContent = citations[nombreAleatoire][1];
}

btn.addEventListener('click', majContenu);